### ISSUE TITLE
Edited message throws error

### ISSUE THREAD

**Issue by errorfourten** [errorfourten/singbusbot#1]
When a telegram message is edited before it is processed by the server, it causes the server to crash

2017-07-30T16:47:09.387600+00:00 app[web.1]: Traceback (most recent call last):
2017-07-30T16:47:09.387663+00:00 app[web.1]:   File "singbusbot.py", line 90, in <module>
2017-07-30T16:47:09.387935+00:00 app[web.1]:     main()
2017-07-30T16:47:09.387939+00:00 app[web.1]:   File "singbusbot.py", line 86, in main
2017-07-30T16:47:09.388241+00:00 app[web.1]:     send_bus_timings(updates)
2017-07-30T16:47:09.388243+00:00 app[web.1]:   File "singbusbot.py", line 38, in send_bus_timings
2017-07-30T16:47:09.388291+00:00 app[web.1]:     busStopCode = update["message"]["text"]
2017-07-30T16:47:09.388316+00:00 app[web.1]: KeyError: 'message'

**Comment by errorfourten** [comment]
Closed. Added exception handling for KeyError to catch updated messages
