### ISSUE TITLE
Database connection gets closed and cannot reopen

### ISSUE THREAD

**Issue by errorfourten** [errorfourten/singbusbot#13]
```
 Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 356, in process_update
    self.dispatch_error(update, e)
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 525, in dispatch_error
    callback(update, CallbackContext.from_error(update, error, self))
  File "singbusbot.py", line 731, in error_callback
    raise context.error
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "singbusbot.py", line 305, in send_bus_timings
    message = check_valid_favourite(update.message)
  File "singbusbot.py", line 178, in check_valid_favourite
    cur = conn.cursor()
psycopg2.InterfaceError: connection already closed
```

**Comment by errorfourten** [comment]
Should try and automatically reopen the connection and retry the incoming request
